#!/usr/local/bin/zsh

# OBSCUR - a script to move downloaded OBSCURUS images and build an MP4 and/or GIF

usage()
{
    echo "usage: moveit [[[-f file ] | [-h]]"
}

list() {
  setopt extendedglob
  pushd ~/Downloads
  ls [0-9]##-[0-9]##.png
  popd
}

mkmp4() {
 #  ffmpeg -r 30 -f image2 -s 500x500 -i "$1-%06d.png" -vcodec libx264 -crf 17 -pix_fmt yuv420p $1.mp4
 # https://hamelot.io/visualization/using-ffmpeg-to-convert-a-set-of-images-into-a-video/
 # -r = frameRate
 ffmpeg -r 15 -f image2 -s 500x500 -pattern_type glob -i '*.png' -vcodec libx264 -crf 17 -pix_fmt yuv420p $1.mp4
}

mkgif() {
  convert -delay 3.33 -loop 0 *.png $1.gif
}

moveit() {
  mkdir $TARGET
  mv $FILENAME*.png $TARGET
  pushd $TARGET
  mkmp4 $FILENAME
#   mkgif $1
  echo "open $TARGET/$FILENAME.mp4"
  popd
}

collect() {
  pushd $TARGET_ROOT
  find [0-9]* -type f -name "[0-9]*.mp4" -exec cp -n {} news \;
  find [0-9]* -type f -name "[0-9]*.gif" -exec cp -n {} news \;
  popd
}

## MAIN

SOURCE=~/Downloads
TARGET_ROOT=$SOURCE/obscur.out
FILENAME=

while [ "$1" != "" ]; do
    case $1 in
        -f | --file )           shift
                                FILENAME=$1
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        -l | --list )           list
                                exit  
                                ;;
        -c | --collect )        collect
                                exit  
                                ;;                                                                
        * )                     usage
                                exit 1
    esac
    shift
done

TARGET=$TARGET_ROOT/$FILENAME

echo $TARGET

# moveit $FILENAME